# Generated by Django 2.1.15 on 2020-06-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20200628_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cr_table',
            name='res_ID',
            field=models.IntegerField(max_length=1000),
        ),
    ]
