# Generated by Django 3.1.2 on 2020-10-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20200628_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('url', models.CharField(max_length=200, unique=True, verbose_name='Url')),
                ('admin_tel', models.CharField(max_length=200, unique=True, verbose_name='Admin Tel')),
                ('admin_email', models.CharField(max_length=200, unique=True, verbose_name='Admin Email')),
                ('token', models.CharField(max_length=32, unique=True, verbose_name='Token')),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'Systems',
            },
        ),
        migrations.AlterField(
            model_name='cr_table',
            name='res_ID',
            field=models.IntegerField(),
        ),
    ]
