# Generated by Django 3.1.2 on 2020-10-21 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20201021_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='User Id')),
                ('ip', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='User Agent')),
                ('referer', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Referer')),
                ('xReferer', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='XReferer')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start Time')),
                ('End_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.system', verbose_name='System')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
    ]
