# Generated by Django 3.1.2 on 2020-10-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='ip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='session',
            name='referer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Referer'),
        ),
        migrations.AlterField(
            model_name='session',
            name='user_agent',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='session',
            name='xReferer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='XReferer'),
        ),
    ]
