# Generated by Django 3.1.2 on 2020-10-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20201021_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CR_TABLE',
        ),
        migrations.DeleteModel(
            name='CRId',
        ),
    ]
