# Generated by Django 3.1.2 on 2020-10-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20201021_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='user_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='User Id'),
        ),
    ]
