# Generated by Django 3.1.2 on 2020-10-26 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_auto_20201026_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Channel Id')),
                ('content_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Content Id')),
                ('content_type_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Content_type_Id')),
                ('service_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Service_Id')),
                ('action_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Action Id')),
                ('time_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Time Code')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
